### ISSUE TITLE
Not able to find fluent automation recorder for Chrome

### ISSUE THREAD

**Issue by nishant7k** [stirno/FluentAutomation#59]
Hi,

I checked the below link for recording the test steps.

http://fluent.stirno.com/2011/11/introducing-the-fluent-automation-recorder/

But not able to find the chrome extension in chrome web store. Is it available? Also i need to search with what name? Quick help on this will be really helpful.

**Comment by pauljz** [comment]
The work we have done on the Fluent Automation Recorder is probably best labeled "proof of concept" - we haven't formally released it just yet. I'm really glad to hear you're interested though!

With Fluent Automation's next major revision release (this is now available as a beta Nuget package and here on GitHub) we'll bring the recorder up to date and release it onto the Chrome store. I don't have an exact timeline for this but probably some time in the next couple weeks.

I'm going to leave this issue open here since some of the integration points still need updated.

**Comment by nishant7k** [comment]
Hello
Thanks for quick response. I will wait for it. Hope to see it soon. Also I am already using the new beta Nuget version of fluent automation. It solves most of my problem. Keep up the good work. Thanks.
