### ISSUE TITLE
Example of I.WaitUntil

### ISSUE THREAD

**Issue by LSTANCZYK** [stirno/FluentAutomation#62]
Can you please provide me with an example of how I can use WaitUntil? I came up with something like this:

```
public static void WaitForText(this FluentAutomation.Interfaces.INativeActionSyntaxProvider I, string waitText)
        {
            string selector = string.Format("*:contains(\"{0}\")", waitText);
            I.WaitUntil( () => I.Find(selector) );
        }
```

and it does not seem to be working for me. 

Thank you in advance.

**Comment by stirno** [comment]
Currently the WaitUntils only work properly with something that will throw an exception. I'm working on extending this to work specifically for element exists type scenarios as well.

If you're wanting to wait for an element (or one of a collection) to exist, this would work (I think. Spit-balling code because I can't directly test it right now):

```
I.WaitUntil(() => I.Expect.Count(1).Of(selector));
```

I've got an I.Expect.Exists(selector) that will find its way in very soon to simplify this type of scenario to:

```
I.Wait.Until(() => I.Expect.Exists(selector));
```

**Comment by stirno** [comment]
Updated the previous comment to something that would actually work, in the versions out on NuGet right now. Currently the only funcs that don't work properly inside of I.WaitUntil() are I.Find() and its variations.

This is now implemented and is the preferred way to wait for an element:

I.WaitUntil(() => I.Expect.Exists(selector));

Actions can be used inside I.WaitUntil also.. for example if you intend to click a button at the first opportunity (questionable how useful this is.. but... ya):

I.WaitUntil(() => I.Click(selector));
