### ISSUE TITLE
Can bootstraping be adopted to accept different browser driver versions?

### ISSUE THREAD

**Issue by object** [stirno/FluentAutomation#73]
I installed FluentAutomation using NuGet package, and it downloaded the latest Selenium.WebDriver package that has version 2.32. But chromedriver.exe that is installed with FluentAutomation expected 2.25.1, so all tests failed. Downgrading WebDriver package fixed the problem, but it's not very flexible because WebDriver version should be set back to the one that the browser driver expects. I wonder if this can be adjusted during the bootstraping so client applications can use latest WebDriver NuGet packages.

**Comment by stirno** [comment]
Wow.. I've done a bad job recently of checking out GH. As mentioned in the other issue, I'm adding user-provided driver executables via config/Settings.*/Bootstrap method to help solve the issue.

I'm also looking at adding some scripts to the NuGet package to grab the latest version of the Driver exe's on install.

**Comment by stirno** [comment]
With the 2.1/2.2 code, a user just needs to place the appropriate driver executables within their project and set to copy always (so they end up in the bin dir). This will become the driver we use, rather than the builtin.

Added specifically to deal with the case where Selenium needs to be updated, but we haven't yet updated Fluent. The original plan I had won't work because of how ChromeDriver is being versioned now so this will have to do for the moment.
