### ISSUE TITLE
NULL reference when converting to IWebElement

### ISSUE THREAD

**Issue by ghost** [stirno/FluentAutomation#96]
It mentions in the documentation that we can find an element and get access to the underlying Selenium object. E.g.:

```
// Find element by selector
var element = I.Find("#searchBox");

// Get reference to underlying IWebElement (Selenium)
var webElement = element() as OpenQA.Selenium.IWebElement;
```

But, this fails for me. webElement is NULL when I try to cast element this way.

Is there another way to get access to the underlying IWebElement?

**Comment by ghost** [comment]
OK, found a work around, its casting hell but it works:

```
var element = I.Find(selector);
var faElement = element() as Element;
var webElement = faElement.WebElement as IWebElement;
```

I assume there's a good reason why the Element.WebElement property isn't exposed via the IElement interface, so I guess the above code isn't good practice?

**Comment by stirno** [comment]
Only reason you can't get directly at the `WebElement` is because `IElement` is a shared abstraction between the Selenium and WatiN providers. We attempt to provide as many useful property accessors on it as possible while maintaining the abstraction (so tests can run on both providers).

In general I would look at `IElement` and see if theres really something you need that isn't there. If there is lets talk about it and maybe we can add it. If its specific Selenium functionality you're going for, then I'd recommend rolling that bit of code into an extension method off of `IElement` to make life a bit easier.

Also, the last cast shouldn't be necessary. `fsElement.WebElement` is already `IWebElement`.

**Comment by ghost** [comment]
Thanks for the comment. The problem is simply a mixture of legacy libraries and the introduction of FluentAutomation. On occasions, I need to pass a `IWebElement` into a legacy library method.

Adding the code as an extension method is a nice idea - I'll take that forward. 

Thanks.

**Comment by stirno** [comment]
Feel free to continue discussing this issue in this thread, I'll respond and help where I can. Closing for stats for now since theres no active issue :)
